environments:
  dev:
    workflows:
      - name: bronze_loader
        tasks:
          - task_key: bronze
            python_wheel_task:
              package_name: school_pipeline
              entry_point: bronze_loader
            existing_cluster_id: "0319-183230-ilr9d2uq"
#            job_cluster_key: dev_cluster

#        job_clusters:
#          - job_cluster_key: dev_cluster
#            new_cluster:
#              spark_version: "14.3.x-scala2.12"
#              node_type_id: "Standard_DS3_v2"
#              num_workers: 1