name: CI/CD for Databrick

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install dbx

#      - name: Run unit test
#        run: pytest -q

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Deploy to Databricks (DEV)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DBX_ENV: dev
        run: |
          dbx deploy --jobs bronze_loader --env dev --no-rebuild
