name: CI/CD for Databrick

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install "setuptools<70"
          pip install "packaging<24"
          pip install wheel
          pip install -r requirements.txt
          pip install dbx==0.7.5

#      - name: Run unit test
#        run: pytest -q

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Deploy to Databricks (DEV)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DBX_ENV: dev
        run: |
          dbx deploy bronze_loader --environment dev --no-rebuild
